services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: fahad@123
      MYSQL_DATABASE: formdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro

  php-fpm:
    image: yourdockerhubusername/formapp-php:latest
    ports: []
    volumes: []
    depends_on:
      - mysql

  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html
      - ./submit.php:/var/www/html/submit.php
    depends_on:
      - php-fpm

volumes:
  mysql_data:

